module.exports.descriptors = [
    'Verde',
    'Antiguo',
    'Petrificado',
    'Rugiente',
    'Cascada',
    'Sereno',
    'Silencioso',
    'Secoya',
    'Ranario',
    'Maple',
    'Brumoso',
    'Ciervo',
    'Montañoso',
    'Oceánico',
    'Marino',
    'Celeste',
    'Polvoriento',
    'Diamante'
];

module.exports.places = [
    'Bosques',
    'Villa',
    'Cañón',
    'Estanque',
    'Campamento en Grupo',
    'Campamento de Caballos',
    'Pueblo Fantasma',
    'Campamento',
    'Campamento Disperso',
    'Zona Remota',
    'Río',
    'Arroyo',
    'A orillas del arroyo',
    'Bahía',
    'Manantial',
    'Costa de la Bahía',
    'Arenas',
    'Campamento de Mulas',
    'Campamento de Caza',
    'Acantilados',
    'Hueco'
];
